### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by JerryWang24** [BiYuqi/webpack-seed#17]
Uncaught Error: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'd:\Jerry2016\work\XXX\webpack-seed\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)

**Comment by BiYuqi** [comment]
@JerryWang24 
npm i node-sass -D
