### ISSUE TITLE
npm dev 报错

### ISSUE THREAD

**Issue by GeekDreamSun** [BiYuqi/webpack-seed#38]
Project is Running at 8080
× ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be an non-empty object.
   -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-seed@1.0.0 dev: `webpack-dev-server --open --inline --mode development --config build/webpack.dev.config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-seed@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BiYuqi** [comment]
@GeekDreamSun 我看下

**Comment by BiYuqi** [comment]
@GeekDreamSun 你好，我这边跑了下是正常的，麻烦提供下:

- 测试平台
- ndoe版本
- 是最新代码吗

我这边用的是mac平台，node版本`v12.18.4`

**Comment by GeekDreamSun** [comment]
windows平台，node版本v14.15.4   是最新代码
如果不是平台的问题  那可能是node版本的问题  我找了好几个类似的 都是跑不起来

**Comment by BiYuqi** [comment]
@GeekDreamSun 稍等，我切个版本做个测试

**Comment by BiYuqi** [comment]
@GeekDreamSun 我用`v14.15.1` 是可以正常使用的，您这边有做代码的改动吗

**Comment by GeekDreamSun** [comment]
我是直接clone下来 运行的

**Comment by BiYuqi** [comment]
@GeekDreamSun [打印下log](https://github.com/BiYuqi/webpack-seed/blob/master/build/webpack.base.config.js#L22) `console.log(utils.entries())` 看下有没有数据打出来。
![image](https://user-images.githubusercontent.com/20992106/104563720-fae64980-5684-11eb-8e8e-05e444ccbd24.png)
从你的报错来看，是这个入口数据没有获取到

**Comment by BiYuqi** [comment]
@GeekDreamSun 

```json
{
  'fonts-page': '/Users/xxxx/SourceCode/webpack-seed/src/views/fonts-page/index.js',
  index: '/Users/xxxx/SourceCode/webpack-seed/src/views/index/index.js',
  'login-page': '/Users/xxxx/SourceCode/webpack-seed/src/views/login-page/index.js',
  'news-page': '/Users/xxxx/SourceCode/webpack-seed/src/views/news/news-page/index.js',
  'test-page': '/Users/xxxx/SourceCode/webpack-seed/src/views/test-page/index.js'
}
```

**Comment by BiYuqi** [comment]
@GeekDreamSun 有可能是使用glob这个库对windows的路径这个块有特殊要求，https://www.npmjs.com/package/glob#windows, 我找个windows做个测试

**Comment by GeekDreamSun** [comment]
![图像 2](https://user-images.githubusercontent.com/20056211/104565025-9fb55680-5686-11eb-8334-0402a219cdf1.jpg)
又chu'x出现了这个问题

**Comment by BiYuqi** [comment]
@GeekDreamSun 我这边用windows 10 64位测试是正常的。唯一的变化时我在功能目录生产了一个`.npmrc`文件，里面用的是淘宝的源 `registry=https://registry.npm.taobao.org`.

有两个建议:
- 生成.npmrc文件，写入淘宝源
- 改用`yarn` 运行项目

**Comment by GeekDreamSun** [comment]
我的 `.npmrc` 是放在的 `C:\Users\xxx`

**Comment by GeekDreamSun** [comment]
> sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver/
phantomjs_cdnurl=https://npm.taobao.org/mirrors/phantomjs/
electron_mirror=https://npm.taobao.org/mirrors/electron/
registry=https://registry.npm.taobao.org/

**Comment by GeekDreamSun** [comment]
哈哈哈  可以类

**Comment by GeekDreamSun** [comment]
yarn 比 npm 好用太多
