### ISSUE TITLE
yarn run serve 又出现了 新的报错

### ISSUE THREAD

**Issue by GeekMakerSun** [BiYuqi/webpack-seed#44]
ERROR in Entry module not found: Error: Can't resolve './src' in 'D:\[Code_Dev]\webpack-seed-1'

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src
Module not found: Error: Can't resolve './src' in 'D:\[Code_Dev]\webpack-seed-1'
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src main[2]
![image](https://user-images.githubusercontent.com/20056211/105655650-6806a400-5efb-11eb-81c6-ab7e7a699dda.png)

**Comment by BiYuqi** [comment]
@GeekMakerSun  window10, nodejs14.x 没发现有什么问题，建议不要使用cnpm

**Comment by GeekMakerSun** [comment]
找到了问题的所在，是文件路径的问题，我的代码放在了`[Code_Dev]` 去掉`[]`问题解决了
