### ISSUE TITLE
具体可以解决什么问题？非spa应用 解决html复用的问题吗?seo？

### ISSUE THREAD

**Issue by liaoliaojun** [BiYuqi/webpack-seed#5]

**Comment by BiYuqi** [comment]
@LIAOTOW 您好, 目前看可以解决非spa应用，html复用的问题. 还有就是工程化开发这块体验也还不错

**Comment by LIAOTOW** [comment]
你的项目里只有一个地方用到jquery了，是为了demo演示用吗，去掉没问题吧。
![image](https://user-images.githubusercontent.com/22748955/51596010-fb82f400-1f32-11e9-8c87-6c4f701d4acf.png)

**Comment by BiYuqi** [comment]
@LIAOTOW 是的，jQuery仅仅是演示用，项目不依赖jQuery

**Comment by LIAOTOW** [comment]
layout的作用是解析ejs的吗?

**Comment by LIAOTOW** [comment]
@BiYuqi  提了一个rp，修改了配置，麻烦看一下。

**Comment by qdchenyixuan** [comment]
@BiYuqi  请问build后是否会影响SEO呢？感谢

**Comment by BiYuqi** [comment]
@qdchenyixuan build后和seo没关系吧，本身项目不是后端渲染，内容一般都是ajax请求渲染的.

**Comment by qdchenyixuan** [comment]
明白了，感谢
